import { Countries } from './country.model';

export var countries: Countries[] = [
  {
    code2: 'AF',
    code3: 'AFG',
    name: 'Afghanistan',
    phoneShow: '+93',
    phone: '+(93)',
  },
  {
    code2: 'AL',
    code3: 'ALB',
    name: 'Albania',
    phoneShow: '+355',
    phone: '+(355)',
  },
  {
    code2: 'DZ',
    code3: 'DZA',
    name: 'Algeria',
    phoneShow: '+213',
    phone: '+(213)',
  },
  {
    code2: 'AS',
    code3: 'ASM',
    name: 'American Samoa',
    phoneShow: '+1-684',
    phone: '+(1-684)',
  },
  {
    code2: 'AD',
    code3: 'AND',
    name: 'Andorra',
    phoneShow: '+376',
    phone: '+(376)',
  },
  {
    code2: 'AO',
    code3: 'AGO',
    name: 'Angola',
    phoneShow: '+244',
    phone: '+(244)',
  },
  {
    code2: 'AI',
    code3: 'AIA',
    name: 'Anguilla',
    phoneShow: '+1-264',
    phone: '+(1-264)',
  },
  {
    code2: 'AQ',
    code3: 'ATA',
    name: 'Antarctica',
    phoneShow: '+672',
    phone: '+(672)',
  },
  {
    code2: 'AG',
    code3: 'ATG',
    name: 'Antigua and Barbuda',
    phoneShow: '+1-268',
    phone: '+(1-268)',
  },
  {
    code2: 'AR',
    code3: 'ARG',
    name: 'Argentina',
    phoneShow: '+54',
    phone: '+(54)',
  },
  {
    code2: 'AM',
    code3: 'ARM',
    name: 'Armenia',
    phoneShow: '+374',
    phone: '+(374)',
  },
  {
    code2: 'AW',
    code3: 'ABW',
    name: 'Aruba',
    phoneShow: '+297',
    phone: '+(297)',
  },
  {
    code2: 'AU',
    code3: 'AUS',
    name: 'Australia',
    phoneShow: '+61',
    phone: '+(61)',
  },
  {
    code2: 'AT',
    code3: 'AUT',
    name: 'Austria',
    phoneShow: '+43',
    phone: '+(43)',
  },
  {
    code2: 'AZ',
    code3: 'AZE',
    name: 'Azerbaijan',
    phoneShow: '+994',
    phone: '+(994)',
  },
  {
    code2: 'BS',
    code3: 'BHS',
    name: 'Bahamas',
    phoneShow: '+1-242',
    phone: '+(1-242)',
  },
  {
    code2: 'BH',
    code3: 'BHR',
    name: 'Bahrain',
    phoneShow: '+973',
    phone: '+(973)',
  },
  {
    code2: 'BD',
    code3: 'BGD',
    name: 'Bangladesh',
    phoneShow: '+880',
    phone: '+(880)',
  },
  {
    code2: 'BB',
    code3: 'BRB',
    name: 'Barbados',
    phoneShow: '+1-246',
    phone: '+(1-246)',
  },
  {
    code2: 'BY',
    code3: 'BLR',
    name: 'Belarus',
    phoneShow: '+375',
    phone: '+(375)',
  },
  {
    code2: 'BE',
    code3: 'BEL',
    name: 'Belgium',
    phoneShow: '+32',
    phone: '+(32)',
  },
  {
    code2: 'BZ',
    code3: 'BLZ',
    name: 'Belize',
    phoneShow: '+501',
    phone: '+(501)',
  },
  {
    code2: 'BJ',
    code3: 'BEN',
    name: 'Benin',
    phoneShow: '+229',
    phone: '+(229)',
  },
  {
    code2: 'BM',
    code3: 'BMU',
    name: 'Bermuda',
    phoneShow: '+1-441',
    phone: '+(1-441)',
  },
  {
    code2: 'BT',
    code3: 'BTN',
    name: 'Bhutan',
    phoneShow: '+975',
    phone: '+(975)',
  },
  {
    code2: 'BO',
    code3: 'BOL',
    name: 'Bolivia',
    phoneShow: '+591',
    phone: '+(591)',
  },
  {
    code2: 'BA',
    code3: 'BIH',
    name: 'Bosnia and Herzegovina',
    phoneShow: '+387',
    phone: '+(387)',
  },
  {
    code2: 'BW',
    code3: 'BWA',
    name: 'Botswana',
    phoneShow: '+267',
    phone: '+(267)',
  },
  {
    code2: 'BR',
    code3: 'BRA',
    name: 'Brazil',
    phoneShow: '+55',
    phone: '+(55)',
  },
  {
    code2: 'IO',
    code3: 'IOT',
    name: 'British Indian Ocean Territory',
    phoneShow: '+246',
    phone: '+(246)',
  },
  {
    code2: 'VG',
    code3: 'VGB',
    name: 'British Virgin Islands',
    phoneShow: '+1-284',
    phone: '+(1-284)',
  },
  {
    code2: 'BN',
    code3: 'BRN',
    name: 'Brunei',
    phoneShow: '+673',
    phone: '+(673)',
  },
  {
    code2: 'BG',
    code3: 'BGR',
    name: 'Bulgaria',
    phoneShow: '+359',
    phone: '+(359)',
  },
  {
    code2: 'BF',
    code3: 'BFA',
    name: 'Burkina Faso',
    phoneShow: '+226',
    phone: '+(226)',
  },
  {
    code2: 'BI',
    code3: 'BDI',
    name: 'Burundi',
    phoneShow: '+257',
    phone: '+(257)',
  },
  {
    code2: 'KH',
    code3: 'KHM',
    name: 'Cambodia',
    phoneShow: '+855',
    phone: '+(855)',
  },
  {
    code2: 'CM',
    code3: 'CMR',
    name: 'Cameroon',
    phoneShow: '+237',
    phone: '+(237)',
  },
  { code2: 'CA', code3: 'CAN', name: 'Canada', phoneShow: '+1', phone: '+(1)' },
  {
    code2: 'CV',
    code3: 'CPV',
    name: 'Cape Verde',
    phoneShow: '+238',
    phone: '+(238)',
  },
  {
    code2: 'KY',
    code3: 'CYM',
    name: 'Cayman Islands',
    phoneShow: '+1-345',
    phone: '+(1-345)',
  },
  {
    code2: 'CF',
    code3: 'CAF',
    name: 'Central African Republic',
    phoneShow: '+236',
    phone: '+(236)',
  },
  {
    code2: 'TD',
    code3: 'TCD',
    name: 'Chad',
    phoneShow: '+235',
    phone: '+(235)',
  },
  {
    code2: 'CL',
    code3: 'CHL',
    name: 'Chile',
    phoneShow: '+56',
    phone: '+(56)',
  },
  {
    code2: 'CN',
    code3: 'CHN',
    name: 'China',
    phoneShow: '+86',
    phone: '+(86)',
  },
  {
    code2: 'CX',
    code3: 'CXR',
    name: 'Christmas Island',
    phoneShow: '+61',
    phone: '+(61)',
  },
  {
    code2: 'CC',
    code3: 'CCK',
    name: 'Cocos Islands',
    phoneShow: '+61',
    phone: '+(61)',
  },
  {
    code2: 'CO',
    code3: 'COL',
    name: 'Colombia',
    phoneShow: '+57',
    phone: '+(57)',
  },
  {
    code2: 'KM',
    code3: 'COM',
    name: 'Comoros',
    phoneShow: '+269',
    phone: '+(269)',
  },
  {
    code2: 'CK',
    code3: 'COK',
    name: 'Cook Islands',
    phoneShow: '+682',
    phone: '+(682)',
  },
  {
    code2: 'CR',
    code3: 'CRI',
    name: 'Costa Rica',
    phoneShow: '+506',
    phone: '+(506)',
  },
  {
    code2: 'HR',
    code3: 'HRV',
    name: 'Croatia',
    phoneShow: '+385',
    phone: '+(385)',
  },
  { code2: 'CU', code3: 'CUB', name: 'Cuba', phoneShow: '+53', phone: '+(53)' },
  {
    code2: 'CW',
    code3: 'CUW',
    name: 'Curacao',
    phoneShow: '+599',
    phone: '+(599)',
  },
  {
    code2: 'CY',
    code3: 'CYP',
    name: 'Cyprus',
    phoneShow: '+357',
    phone: '+(357)',
  },
  {
    code2: 'CZ',
    code3: 'CZE',
    name: 'Czech Republic',
    phoneShow: '+420',
    phone: '+(420)',
  },
  {
    code2: 'CD',
    code3: 'COD',
    name: 'Democratic Republic of the Congo',
    phoneShow: '+243',
    phone: '+(243)',
  },
  {
    code2: 'DK',
    code3: 'DNK',
    name: 'Denmark',
    phoneShow: '+45',
    phone: '+(45)',
  },
  {
    code2: 'DJ',
    code3: 'DJI',
    name: 'Djibouti',
    phoneShow: '+253',
    phone: '+(253)',
  },
  {
    code2: 'DM',
    code3: 'DMA',
    name: 'Dominica',
    phoneShow: '+1-767',
    phone: '+(1-767)',
  },
  {
    code2: 'DO',
    code3: 'DOM',
    name: 'Dominican Republic',
    phoneShow: '+1-809',
    phone: '+(1-809)',
  },
  {
    code2: 'TL',
    code3: 'TLS',
    name: 'East Timor',
    phoneShow: '+670',
    phone: '+(670)',
  },
  {
    code2: 'EC',
    code3: 'ECU',
    name: 'Ecuador',
    phoneShow: '+593',
    phone: '+(593)',
  },
  {
    code2: 'EG',
    code3: 'EGY',
    name: 'Egypt',
    phoneShow: '+20',
    phone: '+(20)',
  },
  {
    code2: 'SV',
    code3: 'SLV',
    name: 'El Salvador',
    phoneShow: '+503',
    phone: '+(503)',
  },
  {
    code2: 'GQ',
    code3: 'GNQ',
    name: 'Equatorial Guinea',
    phoneShow: '+240',
    phone: '+(240)',
  },
  {
    code2: 'ER',
    code3: 'ERI',
    name: 'Eritrea',
    phoneShow: '+291',
    phone: '+(291)',
  },
  {
    code2: 'EE',
    code3: 'EST',
    name: 'Estonia',
    phoneShow: '+372',
    phone: '+(372)',
  },
  {
    code2: 'ET',
    code3: 'ETH',
    name: 'Ethiopia',
    phoneShow: '+251',
    phone: '+(251)',
  },
  {
    code2: 'FK',
    code3: 'FLK',
    name: 'Falkland Islands',
    phoneShow: '+500',
    phone: '+(500)',
  },
  {
    code2: 'FO',
    code3: 'FRO',
    name: 'Faroe Islands',
    phoneShow: '+298',
    phone: '+(298)',
  },
  {
    code2: 'FJ',
    code3: 'FJI',
    name: 'Fiji',
    phoneShow: '+679',
    phone: '+(679)',
  },
  {
    code2: 'FI',
    code3: 'FIN',
    name: 'Finland',
    phoneShow: '+358',
    phone: '+(358)',
  },
  {
    code2: 'FR',
    code3: 'FRA',
    name: 'France',
    phoneShow: '+33',
    phone: '+(33)',
  },
  {
    code2: 'PF',
    code3: 'PYF',
    name: 'French Polynesia',
    phoneShow: '+689',
    phone: '+(689)',
  },
  {
    code2: 'GA',
    code3: 'GAB',
    name: 'Gabon',
    phoneShow: '+241',
    phone: '+(241)',
  },
  {
    code2: 'GM',
    code3: 'GMB',
    name: 'Gambia',
    phoneShow: '+220',
    phone: '+(220)',
  },
  {
    code2: 'GE',
    code3: 'GEO',
    name: 'Georgia',
    phoneShow: '+995',
    phone: '+(995)',
  },
  {
    code2: 'DE',
    code3: 'DEU',
    name: 'Germany',
    phoneShow: '+49',
    phone: '+(49)',
  },
  {
    code2: 'GH',
    code3: 'GHA',
    name: 'Ghana',
    phoneShow: '+233',
    phone: '+(233)',
  },
  {
    code2: 'GI',
    code3: 'GIB',
    name: 'Gibraltar',
    phoneShow: '+350',
    phone: '+(350)',
  },
  {
    code2: 'GR',
    code3: 'GRC',
    name: 'Greece',
    phoneShow: '+30',
    phone: '+(30)',
  },
  {
    code2: 'GL',
    code3: 'GRL',
    name: 'Greenland',
    phoneShow: '+299',
    phone: '+(299)',
  },
  {
    code2: 'GD',
    code3: 'GRD',
    name: 'Grenada',
    phoneShow: '+1-473',
    phone: '+(1-473)',
  },
  {
    code2: 'GU',
    code3: 'GUM',
    name: 'Guam',
    phoneShow: '+1-671',
    phone: '+(1-671)',
  },
  {
    code2: 'GT',
    code3: 'GTM',
    name: 'Guatemala',
    phoneShow: '+502',
    phone: '+(502)',
  },
  {
    code2: 'GG',
    code3: 'GGY',
    name: 'Guernsey',
    phoneShow: '+44-1481',
    phone: '+(44-1481)',
  },
  {
    code2: 'GN',
    code3: 'GIN',
    name: 'Guinea',
    phoneShow: '+224',
    phone: '+(224)',
  },
  {
    code2: 'GW',
    code3: 'GNB',
    name: 'Guinea-Bissau',
    phoneShow: '+245',
    phone: '+(245)',
  },
  {
    code2: 'GY',
    code3: 'GUY',
    name: 'Guyana',
    phoneShow: '+592',
    phone: '+(592)',
  },
  {
    code2: 'HT',
    code3: 'HTI',
    name: 'Haiti',
    phoneShow: '+509',
    phone: '+(509)',
  },
  {
    code2: 'HN',
    code3: 'HND',
    name: 'Honduras',
    phoneShow: '+504',
    phone: '+(504)',
  },
  {
    code2: 'HK',
    code3: 'HKG',
    name: 'Hong Kong',
    phoneShow: '+852',
    phone: '+(852)',
  },
  {
    code2: 'HU',
    code3: 'HUN',
    name: 'Hungary',
    phoneShow: '+36',
    phone: '+(36)',
  },
  {
    code2: 'IS',
    code3: 'ISL',
    name: 'Iceland',
    phoneShow: '+354',
    phone: '+(354)',
  },
  {
    code2: 'IN',
    code3: 'IND',
    name: 'India',
    phoneShow: '+91',
    phone: '+(91)',
  },
  {
    code2: 'ID',
    code3: 'IDN',
    name: 'Indonesia',
    phoneShow: '+62',
    phone: '+(62)',
  },
  { code2: 'IR', code3: 'IRN', name: 'Iran', phoneShow: '+98', phone: '+(98)' },
  {
    code2: 'IQ',
    code3: 'IRQ',
    name: 'Iraq',
    phoneShow: '+964',
    phone: '+(964)',
  },
  {
    code2: 'IE',
    code3: 'IRL',
    name: 'Ireland',
    phoneShow: '+353',
    phone: '+(353)',
  },
  {
    code2: 'IM',
    code3: 'IMN',
    name: 'Isle of Man',
    phoneShow: '+44-1624',
    phone: '+(44-1624)',
  },
  {
    code2: 'IL',
    code3: 'ISR',
    name: 'Israel',
    phoneShow: '+972',
    phone: '+(972)',
  },
  {
    code2: 'IT',
    code3: 'ITA',
    name: 'Italy',
    phoneShow: '+39',
    phone: '+(39)',
  },
  {
    code2: 'CI',
    code3: 'CIV',
    name: 'Ivory Coast',
    phoneShow: '+225',
    phone: '+(225)',
  },
  {
    code2: 'JM',
    code3: 'JAM',
    name: 'Jamaica',
    phoneShow: '+1-876',
    phone: '+(1-876)',
  },
  {
    code2: 'JP',
    code3: 'JPN',
    name: 'Japan',
    phoneShow: '+81',
    phone: '+(81)',
  },
  {
    code2: 'JE',
    code3: 'JEY',
    name: 'Jersey',
    phoneShow: '+44-1534',
    phone: '+(44-1534)',
  },
  {
    code2: 'JO',
    code3: 'JOR',
    name: 'Jordan',
    phoneShow: '+962',
    phone: '+(962)',
  },
  {
    code2: 'KZ',
    code3: 'KAZ',
    name: 'Kazakhstan',
    phoneShow: '+7',
    phone: '+(7)',
  },
  {
    code2: 'KE',
    code3: 'KEN',
    name: 'Kenya',
    phoneShow: '+254',
    phone: '+(254)',
  },
  {
    code2: 'KI',
    code3: 'KIR',
    name: 'Kiribati',
    phoneShow: '+686',
    phone: '+(686)',
  },
  {
    code2: 'XK',
    code3: 'XKX',
    name: 'Kosovo',
    phoneShow: '+383',
    phone: '+(383)',
  },
  {
    code2: 'KW',
    code3: 'KWT',
    name: 'Kuwait',
    phoneShow: '+965',
    phone: '+(965)',
  },
  {
    code2: 'KG',
    code3: 'KGZ',
    name: 'Kyrgyzstan',
    phoneShow: '+996',
    phone: '+(996)',
  },
  {
    code2: 'LA',
    code3: 'LAO',
    name: 'Laos',
    phoneShow: '+856',
    phone: '+(856)',
  },
  {
    code2: 'LV',
    code3: 'LVA',
    name: 'Latvia',
    phoneShow: '+371',
    phone: '+(371)',
  },
  {
    code2: 'LB',
    code3: 'LBN',
    name: 'Lebanon',
    phoneShow: '+961',
    phone: '+(961)',
  },
  {
    code2: 'LS',
    code3: 'LSO',
    name: 'Lesotho',
    phoneShow: '+266',
    phone: '+(266)',
  },
  {
    code2: 'LR',
    code3: 'LBR',
    name: 'Liberia',
    phoneShow: '+231',
    phone: '+(231)',
  },
  {
    code2: 'LY',
    code3: 'LBY',
    name: 'Libya',
    phoneShow: '+218',
    phone: '+(218)',
  },
  {
    code2: 'LI',
    code3: 'LIE',
    name: 'Liechtenstein',
    phoneShow: '+423',
    phone: '+(423)',
  },
  {
    code2: 'LT',
    code3: 'LTU',
    name: 'Lithuania',
    phoneShow: '+370',
    phone: '+(370)',
  },
  {
    code2: 'LU',
    code3: 'LUX',
    name: 'Luxembourg',
    phoneShow: '+352',
    phone: '+(352)',
  },
  {
    code2: 'MO',
    code3: 'MAC',
    name: 'Macau',
    phoneShow: '+853',
    phone: '+(853)',
  },
  {
    code2: 'MK',
    code3: 'MKD',
    name: 'Macedonia',
    phoneShow: '+389',
    phone: '+(389)',
  },
  {
    code2: 'MG',
    code3: 'MDG',
    name: 'Madagascar',
    phoneShow: '+261',
    phone: '+(261)',
  },
  {
    code2: 'MW',
    code3: 'MWI',
    name: 'Malawi',
    phoneShow: '+265',
    phone: '+(265)',
  },
  {
    code2: 'MY',
    code3: 'MYS',
    name: 'Malaysia',
    phoneShow: '+60',
    phone: '+(60)',
  },
  {
    code2: 'MV',
    code3: 'MDV',
    name: 'Maldives',
    phoneShow: '+960',
    phone: '+(960)',
  },
  {
    code2: 'ML',
    code3: 'MLI',
    name: 'Mali',
    phoneShow: '+223',
    phone: '+(223)',
  },
  {
    code2: 'MT',
    code3: 'MLT',
    name: 'Malta',
    phoneShow: '+356',
    phone: '+(356)',
  },
  {
    code2: 'MH',
    code3: 'MHL',
    name: 'Marshall Islands',
    phoneShow: '+692',
    phone: '+(692)',
  },
  {
    code2: 'MR',
    code3: 'MRT',
    name: 'Mauritania',
    phoneShow: '+222',
    phone: '+(222)',
  },
  {
    code2: 'MU',
    code3: 'MUS',
    name: 'Mauritius',
    phoneShow: '+230',
    phone: '+(230)',
  },
  {
    code2: 'YT',
    code3: 'MYT',
    name: 'Mayotte',
    phoneShow: '+262',
    phone: '+(262)',
  },
  {
    code2: 'MX',
    code3: 'MEX',
    name: 'Mexico',
    phoneShow: '+52',
    phone: '+(52)',
  },
  {
    code2: 'FM',
    code3: 'FSM',
    name: 'Micronesia',
    phoneShow: '+691',
    phone: '+(691)',
  },
  {
    code2: 'MD',
    code3: 'MDA',
    name: 'Moldova',
    phoneShow: '+373',
    phone: '+(373)',
  },
  {
    code2: 'MC',
    code3: 'MCO',
    name: 'Monaco',
    phoneShow: '+377',
    phone: '+(377)',
  },
  {
    code2: 'MN',
    code3: 'MNG',
    name: 'Mongolia',
    phoneShow: '+976',
    phone: '+(976)',
  },
  {
    code2: 'ME',
    code3: 'MNE',
    name: 'Montenegro',
    phoneShow: '+382',
    phone: '+(382)',
  },
  {
    code2: 'MS',
    code3: 'MSR',
    name: 'Montserrat',
    phoneShow: '+1-664',
    phone: '+(1-664)',
  },
  {
    code2: 'MA',
    code3: 'MAR',
    name: 'Morocco',
    phoneShow: '+212',
    phone: '+(212)',
  },
  {
    code2: 'MZ',
    code3: 'MOZ',
    name: 'Mozambique',
    phoneShow: '+258',
    phone: '+(258)',
  },
  {
    code2: 'MM',
    code3: 'MMR',
    name: 'Myanmar',
    phoneShow: '+95',
    phone: '+(95)',
  },
  {
    code2: 'NA',
    code3: 'NAM',
    name: 'Namibia',
    phoneShow: '+264',
    phone: '+(264)',
  },
  {
    code2: 'NR',
    code3: 'NRU',
    name: 'Nauru',
    phoneShow: '+674',
    phone: '+(674)',
  },
  {
    code2: 'NP',
    code3: 'NPL',
    name: 'Nepal',
    phoneShow: '+977',
    phone: '+(977)',
  },
  {
    code2: 'NL',
    code3: 'NLD',
    name: 'Netherlands',
    phoneShow: '+31',
    phone: '+(31)',
  },
  {
    code2: 'AN',
    code3: 'ANT',
    name: 'Netherlands Antilles',
    phoneShow: '+599',
    phone: '+(599)',
  },
  {
    code2: 'NC',
    code3: 'NCL',
    name: 'New Caledonia',
    phoneShow: '+687',
    phone: '+(687)',
  },
  {
    code2: 'NZ',
    code3: 'NZL',
    name: 'New Zealand',
    phoneShow: '+64',
    phone: '+(64)',
  },
  {
    code2: 'NI',
    code3: 'NIC',
    name: 'Nicaragua',
    phoneShow: '+505',
    phone: '+(505)',
  },
  {
    code2: 'NE',
    code3: 'NER',
    name: 'Niger',
    phoneShow: '+227',
    phone: '+(227)',
  },
  {
    code2: 'NG',
    code3: 'NGA',
    name: 'Nigeria',
    phoneShow: '+234',
    phone: '+(234)',
  },
  {
    code2: 'NU',
    code3: 'NIU',
    name: 'Niue',
    phoneShow: '+683',
    phone: '+(683)',
  },
  {
    code2: 'KP',
    code3: 'PRK',
    name: 'North Korea',
    phoneShow: '+850',
    phone: '+(850)',
  },
  {
    code2: 'MP',
    code3: 'MNP',
    name: 'Northern Mariana Islands',
    phoneShow: '+1-670',
    phone: '+(1-670)',
  },
  {
    code2: 'NO',
    code3: 'NOR',
    name: 'Norway',
    phoneShow: '+47',
    phone: '+(47)',
  },
  {
    code2: 'OM',
    code3: 'OMN',
    name: 'Oman',
    phoneShow: '+968',
    phone: '+(968)',
  },
  {
    code2: 'PK',
    code3: 'PAK',
    name: 'Pakistan',
    phoneShow: '+92',
    phone: '+(92)',
  },
  {
    code2: 'PW',
    code3: 'PLW',
    name: 'Palau',
    phoneShow: '+680',
    phone: '+(680)',
  },
  {
    code2: 'PS',
    code3: 'PSE',
    name: 'Palestine',
    phoneShow: '+970',
    phone: '+(970)',
  },
  {
    code2: 'PA',
    code3: 'PAN',
    name: 'Panama',
    phoneShow: '+507',
    phone: '+(507)',
  },
  {
    code2: 'PG',
    code3: 'PNG',
    name: 'Papua New Guinea',
    phoneShow: '+675',
    phone: '+(675)',
  },
  {
    code2: 'PY',
    code3: 'PRY',
    name: 'Paraguay',
    phoneShow: '+595',
    phone: '+(595)',
  },
  { code2: 'PE', code3: 'PER', name: 'Peru', phoneShow: '+51', phone: '+(51)' },
  {
    code2: 'PH',
    code3: 'PHL',
    name: 'Philippines',
    phoneShow: '+63',
    phone: '+(63)',
  },
  {
    code2: 'PN',
    code3: 'PCN',
    name: 'Pitcairn',
    phoneShow: '+64',
    phone: '+(64)',
  },
  {
    code2: 'PL',
    code3: 'POL',
    name: 'Poland',
    phoneShow: '+48',
    phone: '+(48)',
  },
  {
    code2: 'PT',
    code3: 'PRT',
    name: 'Portugal',
    phoneShow: '+351',
    phone: '+(351)',
  },
  {
    code2: 'PR',
    code3: 'PRI',
    name: 'Puerto Rico',
    phoneShow: '+1-787',
    phone: '+(1-787)',
  },
  {
    code2: 'QA',
    code3: 'QAT',
    name: 'Qatar',
    phoneShow: '+974',
    phone: '+(974)',
  },
  {
    code2: 'CG',
    code3: 'COG',
    name: 'Republic of the Congo',
    phoneShow: '+242',
    phone: '+(242)',
  },
  {
    code2: 'RE',
    code3: 'REU',
    name: 'Reunion',
    phoneShow: '+262',
    phone: '+(262)',
  },
  {
    code2: 'RO',
    code3: 'ROU',
    name: 'Romania',
    phoneShow: '+40',
    phone: '+(40)',
  },
  { code2: 'RU', code3: 'RUS', name: 'Russia', phoneShow: '+7', phone: '+(7)' },
  {
    code2: 'RW',
    code3: 'RWA',
    name: 'Rwanda',
    phoneShow: '+250',
    phone: '+(250)',
  },
  {
    code2: 'BL',
    code3: 'BLM',
    name: 'Saint Barthelemy',
    phoneShow: '+590',
    phone: '+(590)',
  },
  {
    code2: 'SH',
    code3: 'SHN',
    name: 'Saint Helena',
    phoneShow: '+290',
    phone: '+(290)',
  },
  {
    code2: 'KN',
    code3: 'KNA',
    name: 'Saint Kitts and Nevis',
    phoneShow: '+1-869',
    phone: '+(1-869)',
  },
  {
    code2: 'LC',
    code3: 'LCA',
    name: 'Saint Lucia',
    phoneShow: '+1-758',
    phone: '+(1-758)',
  },
  {
    code2: 'MF',
    code3: 'MAF',
    name: 'Saint Martin',
    phoneShow: '+590',
    phone: '+(590)',
  },
  {
    code2: 'PM',
    code3: 'SPM',
    name: 'Saint Pierre and Miquelon',
    phoneShow: '+508',
    phone: '+(508)',
  },
  {
    code2: 'VC',
    code3: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    phoneShow: '+1-784',
    phone: '+(1-784)',
  },
  {
    code2: 'WS',
    code3: 'WSM',
    name: 'Samoa',
    phoneShow: '+685',
    phone: '+(685)',
  },
  {
    code2: 'SM',
    code3: 'SMR',
    name: 'San Marino',
    phoneShow: '+378',
    phone: '+(378)',
  },
  {
    code2: 'ST',
    code3: 'STP',
    name: 'Sao Tome and Principe',
    phoneShow: '+239',
    phone: '+(239)',
  },
  {
    code2: 'SA',
    code3: 'SAU',
    name: 'Saudi Arabia',
    phoneShow: '+966',
    phone: '+(966)',
  },
  {
    code2: 'SN',
    code3: 'SEN',
    name: 'Senegal',
    phoneShow: '+221',
    phone: '+(221)',
  },
  {
    code2: 'RS',
    code3: 'SRB',
    name: 'Serbia',
    phoneShow: '+381',
    phone: '+(381)',
  },
  {
    code2: 'SC',
    code3: 'SYC',
    name: 'Seychelles',
    phoneShow: '+248',
    phone: '+(248)',
  },
  {
    code2: 'SL',
    code3: 'SLE',
    name: 'Sierra Leone',
    phoneShow: '+232',
    phone: '+(232)',
  },
  {
    code2: 'SG',
    code3: 'SGP',
    name: 'Singapore',
    phoneShow: '+65',
    phone: '+(65)',
  },
  {
    code2: 'SX',
    code3: 'SXM',
    name: 'Sint Maarten',
    phoneShow: '+1-721',
    phone: '+(1-721)',
  },
  {
    code2: 'SK',
    code3: 'SVK',
    name: 'Slovakia',
    phoneShow: '+421',
    phone: '+(421)',
  },
  {
    code2: 'SI',
    code3: 'SVN',
    name: 'Slovenia',
    phoneShow: '+386',
    phone: '+(386)',
  },
  {
    code2: 'SB',
    code3: 'SLB',
    name: 'Solomon Islands',
    phoneShow: '+677',
    phone: '+(677)',
  },
  {
    code2: 'SO',
    code3: 'SOM',
    name: 'Somalia',
    phoneShow: '+252',
    phone: '+(252)',
  },
  {
    code2: 'ZA',
    code3: 'ZAF',
    name: 'South Africa',
    phoneShow: '+27',
    phone: '+(27)',
  },
  {
    code2: 'KR',
    code3: 'KOR',
    name: 'South Korea',
    phoneShow: '+82',
    phone: '+(82)',
  },
  {
    code2: 'SS',
    code3: 'SSD',
    name: 'South Sudan',
    phoneShow: '+211',
    phone: '+(211)',
  },
  {
    code2: 'ES',
    code3: 'ESP',
    name: 'Spain',
    phoneShow: '+34',
    phone: '+(34)',
  },
  {
    code2: 'LK',
    code3: 'LKA',
    name: 'Sri Lanka',
    phoneShow: '+94',
    phone: '+(94)',
  },
  {
    code2: 'SD',
    code3: 'SDN',
    name: 'Sudan',
    phoneShow: '+249',
    phone: '+(249)',
  },
  {
    code2: 'SR',
    code3: 'SUR',
    name: 'Suriname',
    phoneShow: '+597',
    phone: '+(597)',
  },
  {
    code2: 'SJ',
    code3: 'SJM',
    name: 'Svalbard and Jan Mayen',
    phoneShow: '+47',
    phone: '+(47)',
  },
  {
    code2: 'SZ',
    code3: 'SWZ',
    name: 'Swaziland',
    phoneShow: '+268',
    phone: '+(268)',
  },
  {
    code2: 'SE',
    code3: 'SWE',
    name: 'Sweden',
    phoneShow: '+46',
    phone: '+(46)',
  },
  {
    code2: 'CH',
    code3: 'CHE',
    name: 'Switzerland',
    phoneShow: '+41',
    phone: '+(41)',
  },
  {
    code2: 'SY',
    code3: 'SYR',
    name: 'Syria',
    phoneShow: '+963',
    phone: '+(963)',
  },
  {
    code2: 'TW',
    code3: 'TWN',
    name: 'Taiwan',
    phoneShow: '+886',
    phone: '+(886)',
  },
  {
    code2: 'TJ',
    code3: 'TJK',
    name: 'Tajikistan',
    phoneShow: '+992',
    phone: '+(992)',
  },
  {
    code2: 'TZ',
    code3: 'TZA',
    name: 'Tanzania',
    phoneShow: '+255',
    phone: '+(255)',
  },
  {
    code2: 'TH',
    code3: 'THA',
    name: 'Thailand',
    phoneShow: '+66',
    phone: '+(66)',
  },
  {
    code2: 'TG',
    code3: 'TGO',
    name: 'Togo',
    phoneShow: '+228',
    phone: '+(228)',
  },
  {
    code2: 'TK',
    code3: 'TKL',
    name: 'Tokelau',
    phoneShow: '+690',
    phone: '+(690)',
  },
  {
    code2: 'TO',
    code3: 'TON',
    name: 'Tonga',
    phoneShow: '+676',
    phone: '+(676)',
  },
  {
    code2: 'TT',
    code3: 'TTO',
    name: 'Trinidad and Tobago',
    phoneShow: '+1-868',
    phone: '+(1-868)',
  },
  {
    code2: 'TN',
    code3: 'TUN',
    name: 'Tunisia',
    phoneShow: '+216',
    phone: '+(216)',
  },
  {
    code2: 'TR',
    code3: 'TUR',
    name: 'Turkey',
    phoneShow: '+90',
    phone: '+(90)',
  },
  {
    code2: 'TM',
    code3: 'TKM',
    name: 'Turkmenistan',
    phoneShow: '+993',
    phone: '+(993)',
  },
  {
    code2: 'TC',
    code3: 'TCA',
    name: 'Turks and Caicos Islands',
    phoneShow: '+1-649',
    phone: '+(1-649)',
  },
  {
    code2: 'TV',
    code3: 'TUV',
    name: 'Tuvalu',
    phoneShow: '+688',
    phone: '+(688)',
  },
  {
    code2: 'VI',
    code3: 'VIR',
    name: 'U.S. Virgin Islands',
    phoneShow: '+1-340',
    phone: '+(1-340)',
  },
  {
    code2: 'UG',
    code3: 'UGA',
    name: 'Uganda',
    phoneShow: '+256',
    phone: '+(256)',
  },
  {
    code2: 'UA',
    code3: 'UKR',
    name: 'Ukraine',
    phoneShow: '+380',
    phone: '+(380)',
  },
  {
    code2: 'AE',
    code3: 'ARE',
    name: 'United Arab Emirates',
    phoneShow: '+971',
    phone: '+(971)',
  },
  {
    code2: 'GB',
    code3: 'GBR',
    name: 'United Kingdom',
    phoneShow: '+44',
    phone: '+(44)',
  },
  {
    code2: 'US',
    code3: 'USA',
    name: 'United States',
    phoneShow: '+1',
    phone: '+(1)',
  },
  {
    code2: 'UY',
    code3: 'URY',
    name: 'Uruguay',
    phoneShow: '+598',
    phone: '+(598)',
  },
  {
    code2: 'UZ',
    code3: 'UZB',
    name: 'Uzbekistan',
    phoneShow: '+998',
    phone: '+(998)',
  },
  {
    code2: 'VU',
    code3: 'VUT',
    name: 'Vanuatu',
    phoneShow: '+678',
    phone: '+(678)',
  },
  {
    code2: 'VA',
    code3: 'VAT',
    name: 'Vatican',
    phoneShow: '+379',
    phone: '+(379)',
  },
  {
    code2: 'VE',
    code3: 'VEN',
    name: 'Venezuela',
    phoneShow: '+58',
    phone: '+(58)',
  },
  {
    code2: 'VN',
    code3: 'VNM',
    name: 'Vietnam',
    phoneShow: '+84',
    phone: '+(84)',
  },
  {
    code2: 'WF',
    code3: 'WLF',
    name: 'Wallis and Futuna',
    phoneShow: '+681',
    phone: '+(681)',
  },
  {
    code2: 'EH',
    code3: 'ESH',
    name: 'Western Sahara',
    phoneShow: '+212',
    phone: '+(212)',
  },
  {
    code2: 'YE',
    code3: 'YEM',
    name: 'Yemen',
    phoneShow: '+967',
    phone: '+(967)',
  },
  {
    code2: 'ZM',
    code3: 'ZMB',
    name: 'Zambia',
    phoneShow: '+260',
    phone: '+(260)',
  },
  {
    code2: 'ZW',
    code3: 'ZWE',
    name: 'Zimbabwe',
    phoneShow: '+263',
    phone: '+(263)',
  },
];
